### ISSUE TITLE
Random number is always 0

### ISSUE THREAD

**Issue by RafaelVidaurre** [smartcontractkit/hardhat-starter-kit#18] opened 2021-05-25 12:33 UTC
First of all, thanks for putting this demo repo together.

I'm trying to test some smart contracts that interact with VRF locally. Even though I think I've followed the instructions correctly, I keep getting `0` as the randomly generated number, regardless of the seed.

Looking at the code,  it seems like this line would be logging `You'll either need to wait another minute, or fix something!`, but it won't do that either, since the result is being casted into a string.

```javascript
        const vrfConsumerContract = new ethers.Contract(contractAddr, RandomNumberConsumer.interface, signer)
        let result = BigInt(await vrfConsumerContract.randomResult()).toString()
        console.log('Random Number is: ', result)
        if (result == 0 && ['hardhat', 'localhost', 'ganache'].indexOf(network.name) == 0) {
            console.log("You'll either need to wait another minute, or fix something!")
        }
``` 

Is there anything I could be missing?

Thanks!

**Comment by pappas999** [comment] 2021-05-27 03:30
Hi @RafaelVidaurre , thanks for raising this. Looks to be a bug with the logic around the ==0 vs == -1.  That if statement should only return true if you're not working on a local network (ie you're working on a public network that's integrated to a real Chainlink network).

If working on a local network, you can't really use the **'request-random-number'** task, because there's no integration to a real Chainlink network. Take a look at the unit tests to see what can be done when working locally

Also, if you'd like to contribute to improving our hardhat starter kit, you can [raise a PR](https://github.com/smartcontractkit/hardhat-starter-kit/pulls) on our starter kit to correct the bug, and we can then review it and have it merged to the main repository

**Comment by RafaelVidaurre** [comment] 2021-05-27 17:56
@pappas999 thanks for clarifying this, I understand now what my options are. I'll see if I can submit a PR to improve this part. So, more than the random number = `0` being a bug, it is a limitation when working locally. So I guess the only real issue here is the logic by which we output these messages to the console, and maybe that we should mention the differences between working locally vs working with a test net for development.

**Comment by pappas999** [comment] 2021-05-28 00:11
Correct, looks like the issue is in the logic as to whether to print that statement to the console or not, because it's looking for when it's a local network, whereas it should be looking for when it's not a local network (and we have a 0 result)

**Comment by PatrickAlphaC** [comment] 2021-07-13 12:50
Closing this for now, but feel free to follow up.

**Closed by PatrickAlphaC** 2021-07-13 12:50 UTC
